name: Lint & Test
on: push
jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install packages
      run: npm install --only=dev

    - name: Run linter
      run: npm run lint

  test:
    name: Test on Go ${{ matrix.go_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: [1.11, 1.12]
        os: [ubuntu-latest]
        atom_channel: ['stable', 'beta']
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go_version }}
      id: go

    - name: Get Revive
      run: go get -v -u github.com/mgechev/revive

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run tests
      env:
        ATOM_CHANNEL: ${{ matrix.atom_channel }}
        ATOM_LINT_WITH_BUNDLED_NODE: 'true'
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
        chmod u+x build-package.sh
        ./build-package.sh
