name: Test

on: push

jobs:
  test:
    name: Test on Atom ${{ matrix.atom_channel }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        atom_channel: ['stable', 'beta']

    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - name: Get Revive
      run: go get -v -u github.com/mgechev/revive@v1

    - name: Check out code into the package directory
      uses: actions/checkout@v1

    - name: Set up Atom
      uses: UziTech/action-setup-atom@v1
      with:
        channel: ${{ matrix.channel }}

    - name: Get versions
      run: atom -v && apm -v

    - name: Install dependencies
      run: apm ci

    - name: Run tests
      run: apm test
