name: Test

on:
  push:
    paths:
      - '**'
      - '!**.md'
      - '!LICENSE'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v3.1.0

    - name: Set up Node
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 12

    - name: Install packages
      run: npm ci

    - name: Run linter
      run: npm run lint

  test:
    name: Test on Atom ${{ matrix.version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ['stable', 'beta']
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Get Revive
      run: go get -v -u github.com/mgechev/revive@v1

    - name: Check out
      uses: actions/checkout@v3.1.0

    - name: Set up Atom
      uses: UziTech/action-setup-atom@v2
      with:
        version: ${{ matrix.version }}

    - name: Get versions
      run: atom -v && apm -v

    - name: Install dependencies
      run: apm ci

    - name: Run tests
      run: atom --test spec
